### ISSUE TITLE
Sign with a key?

### ISSUE THREAD

**Issue by ughstudios** [cryptocoinjs/sha256#9]
Is there an example of how to use this library to sign a string with a key? I need to sign my sha256 hash with a special api key i have

**Comment by junderw** [comment]
1. Please read the README. It says in big letters this repo is deprecated. You should always read the README and search prior issues BEFORE asking a question. The readme recommends using https://github.com/crypto-browserify/sha.js
2. There is no standard for "signing" using sha256. It is a hash digest algorithm, so any "signing" protocol your API uses is most likely described in the API documents of the API you are using. Most methods I know of involve concatenating the request body with your API secret then hashing it, but you will have to check your API's documentation.
